spring:
  application:
    name: customer-service

server:
  port: 8085


management:
  endpoints:
    web:
      exposure:        include: "*"
  endpoint:    health:      show-details: always        metrics:
    tags:      application: ${spring.application.name}
    export:      azuremonitor:        instrumentation-key: "XXXXXX"
        
azure:
  application-insights.instrumentation-key: "XXXXXX"         